default.nix: stop using gnome3.vte
The alias was changed to an error. Trying to evaluate ate in a system
configuration with a recent (4a94071fb3e4fddc8b98dc13104ac720eceb728c)
nixpkgs fails like this:

> error: The ‘gnome.vte’ alias was removed on 2022-01-13. Please use ‘pkgs.vte’ directly.

With this change, my system evaluates successfully again.